# week08/k8s/order-db.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db-deployment-w08-aks
  namespace: ecomm-w08-aks
  labels:
    app: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w08-aks
              key: ORDERS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w08-aks
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w08-aks
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: order-db-service-w08-aks
  namespace: ecomm-w08-aks
  labels:
    app: order-db
spec:
  selector:
    app: order-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
