# week08/k8s/product-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-w08e1
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service-container
        image: <ACR_NAME>/<IMAGE_NAME>:<IMAGE_TAG>
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        # Database connection details
        - name: POSTGRES_HOST
          value: product-db-service-w08e1
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w08e1
              key: PRODUCTS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w08e1 # Secret name matches
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w08e1 # Secret name matches
              key: POSTGRES_PASSWORD
        - name: AZURE_STORAGE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w08e1 # Secret name matches
              key: AZURE_STORAGE_ACCOUNT_NAME
        - name: AZURE_STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w08e1 # Secret name matches
              key: AZURE_STORAGE_ACCOUNT_KEY
        - name: AZURE_STORAGE_CONTAINER_NAME
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w08e1 # ConfigMap name matches
              key: AZURE_STORAGE_CONTAINER_NAME
        - name: AZURE_SAS_TOKEN_EXPIRY_HOURS
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w08e1 # ConfigMap name matches
              key: AZURE_SAS_TOKEN_EXPIRY_HOURS
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-w08e1
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
